#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# Notebook Studio — One-Line Installer
#
# Usage:
#   curl -fsSL "https://github.com/thaonv7995/notebook/releases/latest/download/install.sh" | sh -s -- "thaonv7995/notebook"
#
# What it does:
#   1. Downloads the latest release tarball
#   2. Extracts to ~/notebook-studio (or $INSTALL_DIR)
#   3. Installs production npm dependencies
#   4. Generates a random admin password
#   5. Creates .env with credentials
#   6. Starts the server on port 27972
# ──────────────────────────────────────────────────────────────

set -euo pipefail

# ─── Configuration ───
REPO="${1:-}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/notebook-studio}"
PORT="${PORT:-27972}"
ADMIN_EMAIL="admin@notebook.com"

# ─── Colors ───
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}ℹ${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1" >&2; }

# ─── Preflight Checks ───
if [ -z "$REPO" ]; then
  err "Missing repository argument."
  echo ""
  echo "Usage:"
  echo "  curl -fsSL \"https://github.com/thaonv7995/notebook/releases/latest/download/install.sh\" | sh -s -- \"thaonv7995/notebook\""
  echo ""
  exit 1
fi

for cmd in curl tar node npm; do
  if ! command -v "$cmd" &>/dev/null; then
    err "Required command '$cmd' not found. Please install it first."
    exit 1
  fi
done

NODE_MAJOR=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 18 ]; then
  err "Node.js v18+ is required (found $(node -v))."
  exit 1
fi

# ─── Banner ───
echo ""
echo -e "${CYAN}${BOLD}  ┌───────────────────────────────────────┐${NC}"
echo -e "${CYAN}${BOLD}  │       📓 Notebook Studio Installer     │${NC}"
echo -e "${CYAN}${BOLD}  └───────────────────────────────────────┘${NC}"
echo ""

# ─── Detect Latest Release ───
info "Fetching latest release from ${BOLD}${REPO}${NC}..."
RELEASE_URL="https://api.github.com/repos/${REPO}/releases/latest"
RELEASE_JSON=$(curl -fsSL "$RELEASE_URL" 2>/dev/null || true)

if [ -z "$RELEASE_JSON" ]; then
  err "Could not fetch release info from $RELEASE_URL"
  exit 1
fi

TAG=$(echo "$RELEASE_JSON" | grep '"tag_name"' | head -1 | sed 's/.*"tag_name"[[:space:]]*:[[:space:]]*"//' | sed 's/".*//')
TARBALL_URL="https://github.com/${REPO}/releases/download/${TAG}/notebook-studio-${TAG}.tar.gz"

if [ -z "$TAG" ]; then
  err "Could not determine the latest release tag."
  exit 1
fi

ok "Latest release: ${BOLD}${TAG}${NC}"

# ─── Download & Extract ───
info "Downloading ${BOLD}notebook-studio-${TAG}.tar.gz${NC}..."
TMPDIR=$(mktemp -d)
TARBALL="$TMPDIR/notebook-studio.tar.gz"

curl -fSL "$TARBALL_URL" -o "$TARBALL" || {
  err "Failed to download release tarball."
  rm -rf "$TMPDIR"
  exit 1
}

ok "Downloaded successfully."

info "Installing to ${BOLD}${INSTALL_DIR}${NC}..."
mkdir -p "$INSTALL_DIR"
tar -xzf "$TARBALL" -C "$INSTALL_DIR" --strip-components=1

rm -rf "$TMPDIR"
ok "Files extracted."

# ─── Install Dependencies ───
info "Installing Node.js dependencies (production)..."
cd "$INSTALL_DIR"
npm install --omit=dev --ignore-scripts 2>/dev/null
ok "Dependencies installed."

# ─── Generate Credentials ───
ADMIN_PASS=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#$%' </dev/urandom | head -c 16 || true)
JWT_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48 || true)

if [ -f "$INSTALL_DIR/.env" ]; then
  warn "Existing .env found — backing up to .env.bak"
  cp "$INSTALL_DIR/.env" "$INSTALL_DIR/.env.bak"
fi

cat > "$INSTALL_DIR/.env" <<EOF
# Notebook Studio — Server Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
ADMIN_USERNAME=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASS}
NODE_ENV=production
EOF

chmod 600 "$INSTALL_DIR/.env"
ok "Credentials generated."

# ─── Start Server ───
info "Starting Notebook Studio on port ${PORT}..."
cd "$INSTALL_DIR"
NODE_ENV=production node server/index.js &
SERVER_PID=$!

# Wait for server to boot
sleep 2
if kill -0 "$SERVER_PID" 2>/dev/null; then
  ok "Server is running (PID: ${SERVER_PID})."
else
  err "Server failed to start. Check logs above."
  exit 1
fi

# ─── Done ───
echo ""
echo -e "${GREEN}${BOLD}  ┌───────────────────────────────────────────────────┐${NC}"
echo -e "${GREEN}${BOLD}  │  ✅ Notebook Studio installed successfully!       │${NC}"
echo -e "${GREEN}${BOLD}  └───────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${BOLD}URL:${NC}       http://localhost:${PORT}"
echo -e "  ${BOLD}Username:${NC}  ${CYAN}${ADMIN_EMAIL}${NC}"
echo -e "  ${BOLD}Password:${NC}  ${CYAN}${ADMIN_PASS}${NC}"
echo -e "  ${BOLD}Install:${NC}   ${INSTALL_DIR}"
echo ""
echo -e "  ${YELLOW}⚠ Save the password above — it will not be shown again.${NC}"
echo ""
echo -e "  To stop:   ${BOLD}kill ${SERVER_PID}${NC}"
echo -e "  To start:  ${BOLD}cd ${INSTALL_DIR} && NODE_ENV=production node server/index.js${NC}"
echo ""
