/**
 * DOM Elements Cache and Helper Utilities
 */

let cachedEls = null;

export function getEls() {
  if (cachedEls) return cachedEls;

  cachedEls = {
    // Views
    libraryView: document.querySelector('#libraryView'),
    notebookView: document.querySelector('#notebookView'),
    readerHeader: document.querySelector('.reader-header'),
    readerHeaderRight: document.querySelector('.reader-header-right'),
    editorToolbar: document.querySelector('.editor-toolbar'),

    // Library View
    libBrandLogo: document.querySelector('#libBrandLogo'),
    libSearchInput: document.querySelector('#libSearchInput'),
    libCategoryFilter: document.querySelector('#libCategoryFilter'),
    btnOpenNewBookModal: document.querySelector('#btnOpenNewBookModal'),
    booksGrid: document.querySelector('#booksGrid'),
    libBookCount: document.querySelector('#libBookCount'),
    libSectionTitle: document.querySelector('.lib-section-title'),

    // Reader View Top Header
    btnBackToLibrary: document.querySelector('#btnBackToLibrary'),
    openBookTitle: document.querySelector('#openBookTitle'),
    btnTogglePageDrawer: document.querySelector('#btnTogglePageDrawer'),
    btnPrevPage: document.querySelector('#btnPrevPage'),
    btnNextPage: document.querySelector('#btnNextPage'),
    readerPageInput: document.querySelector('#readerPageInput'),
    readerTotalPages: document.querySelector('#readerTotalPages'),
    btnZoomOut: document.querySelector('#btnZoomOut'),
    btnZoomIn: document.querySelector('#btnZoomIn'),
    readerScaleValue: document.querySelector('#readerScaleValue'),
    btnFitPage: document.querySelector('#btnFitPage'),
    btnFitWidth: document.querySelector('#btnFitWidth'),
    btnMode1Page: document.querySelector('#btnMode1Page'),
    btnMode2Pages: document.querySelector('#btnMode2Pages'),
    readerTemplateSelect: document.querySelector('#readerTemplateSelect'),
    readerToneSelect: document.querySelector('#readerToneSelect'),
    readerTextureSelect: document.querySelector('#readerTextureSelect'),
    btnAddPage: document.querySelector('#btnAddPage'),
    btnToggleSound: document.querySelector('#btnToggleSound'),
    btnToggleFormatToolbar: document.querySelector('#btnToggleFormatToolbar'),
    btnToggleFullscreen: document.querySelector('#btnToggleFullscreen'),
    saveStatus: document.querySelector('#save-status'),
    saveStatusText: document.querySelector('#save-status-text'),

    // Workspace & Spread
    openBookWorkspace: document.querySelector('#openBookWorkspace'),
    bookDeskScaler: document.querySelector('#bookDeskScaler'),
    bookSpreadCasing: document.querySelector('#bookSpreadCasing'),
    leftPageSheet: document.querySelector('#leftPageSheet'),
    rightPageSheet: document.querySelector('#rightPageSheet'),
    leftPageLangTag: document.querySelector('#leftPageLangTag'),
    rightPageLangTag: document.querySelector('#rightPageLangTag'),
    leftEditorContainer: document.querySelector('#leftEditorContainer'),
    rightEditorContainer: document.querySelector('#rightEditorContainer'),
    leftPageFooterTitle: document.querySelector('#leftPageFooterTitle'),
    rightPageFooterTitle: document.querySelector('#rightPageFooterTitle'),
    leftPageFooterNum: document.querySelector('#leftPageFooterNum'),
    rightPageFooterNum: document.querySelector('#rightPageFooterNum'),
    bookCenterSpine: document.querySelector('#bookCenterSpine'),
    bookFocusRibbon: document.querySelector('#bookFocusRibbon'),

    // Formatting Toolbar
    fmtBold: document.querySelector('#fmt-bold'),
    fmtItalic: document.querySelector('#fmt-italic'),
    fmtUnderline: document.querySelector('#fmt-underline'),
    fmtStrike: document.querySelector('#fmt-strike'),
    fmtColorBtn: document.querySelector('#fmt-color-btn'),
    fmtColorPalette: document.querySelector('#fmt-color-palette'),
    currentColorBar: document.querySelector('#current-color-bar'),
    fmtBgBtn: document.querySelector('#fmt-bg-btn'),
    fmtBgPalette: document.querySelector('#fmt-bg-palette'),
    currentBgBar: document.querySelector('#current-bg-bar'),
    fmtBadgeBtn: document.querySelector('#fmt-badge-btn'),
    fmtClear: document.querySelector('#fmt-clear'),
    fmtH1: document.querySelector('#fmt-h1'),
    fmtH2: document.querySelector('#fmt-h2'),
    fmtH3: document.querySelector('#fmt-h3'),
    fmtBullet: document.querySelector('#fmt-bullet'),
    fmtNumber: document.querySelector('#fmt-number'),
    fmtTodo: document.querySelector('#fmt-todo'),
    fmtQuote: document.querySelector('#fmt-quote'),
    fmtCode: document.querySelector('#fmt-code'),
    fmtHr: document.querySelector('#fmt-hr'),
    fmtUndo: document.querySelector('#fmt-undo'),
    fmtRedo: document.querySelector('#fmt-redo'),
    fmtFontFamily: document.querySelector('#fmt-font-family'),
    fontDecreaseBtn: document.querySelector('#font-decrease'),
    fontIncreaseBtn: document.querySelector('#font-increase'),
    fontSizeLabel: document.querySelector('#font-size-label'),
    fontResetBtn: document.querySelector('#font-reset'),
    btnLineHeightSettings: document.querySelector('#btnLineHeightSettings'),
    lineHeightMenu: document.querySelector('#line-height-menu'),
    lineHeightLabel: document.querySelector('#line-height-label'),
    btnDeleteCurrentPage: document.querySelector('#btnDeleteCurrentPage'),
    btnRenameBook: document.querySelector('#btnRenameBook'),
    btnCopyBookLink: document.querySelector('#btnCopyBookLink'),
    btnDeleteCurrentBook: document.querySelector('#btnDeleteCurrentBook'),
    exportPrintBtn: document.querySelector('#export-print'),
    pdfExportMenu: document.querySelector('#pdf-export-menu'),
    exportPdfWithCoverBtn: document.querySelector('#export-pdf-with-cover'),
    exportPdfContentOnlyBtn: document.querySelector('#export-pdf-content-only'),
    btnToolbarMore: document.querySelector('#btnToolbarMore'),
    toolbarMoreMenu: document.querySelector('#toolbarMoreMenu'),
    btnCollapseToolbar: document.querySelector('#btnCollapseToolbar'),
    fullscreenRail: document.querySelector('#fullscreenRail'),
    btnFullscreenExit: document.querySelector('#btnFullscreenExit'),
    btnFullscreenChrome: document.querySelector('#btnFullscreenChrome'),
    fsRailBtnPageList: document.querySelector('#fsRailBtnPageList'),
    btnFullscreenPrev: document.querySelector('#btnFullscreenPrev'),
    btnFullscreenNext: document.querySelector('#btnFullscreenNext'),
    btnFullscreenAddPage: document.querySelector('#btnFullscreenAddPage'),
    fullscreenPageIndicator: document.querySelector('#fullscreenPageIndicator'),
    fsPageCur: document.querySelector('#fsPageCur'),
    fsPageTotal: document.querySelector('#fsPageTotal'),
    btnFullscreenMode1Page: document.querySelector('#btnFullscreenMode1Page'),
    btnFullscreenMode2Pages: document.querySelector('#btnFullscreenMode2Pages'),
    btnFullscreenZoomIn: document.querySelector('#btnFullscreenZoomIn'),
    fullscreenScaleValue: document.querySelector('#fullscreenScaleValue'),
    btnFullscreenZoomOut: document.querySelector('#btnFullscreenZoomOut'),
    btnFullscreenFitPage: document.querySelector('#btnFullscreenFitPage'),
    btnFullscreenFitWidth: document.querySelector('#btnFullscreenFitWidth'),
    fullscreenSaveStatus: document.querySelector('#fullscreenSaveStatus'),
    fullscreenToolsPanel: document.querySelector('#fullscreenToolsPanel'),
    btnCloseFsPanel: document.querySelector('#btnCloseFsPanel'),
    btnFsTplCornell: document.querySelector('#btnFsTplCornell'),
    btnFsTplWork: document.querySelector('#btnFsTplWork'),
    btnFsTplNormal: document.querySelector('#btnFsTplNormal'),

    // Page Drawer
    pageNavDrawer: document.querySelector('#pageNavDrawer'),
    pageNavBackdrop: document.querySelector('#pageNavBackdrop'),
    btnClosePageDrawer: document.querySelector('#btnClosePageDrawer'),
    pageDrawerList: document.querySelector('#pageDrawerList'),
    pageDrawerCount: document.querySelector('#pageDrawerCount'),
    pageDrawerSearch: document.querySelector('#pageDrawerSearch'),
    btnDrawerAddPage: document.querySelector('#btnDrawerAddPage'),

    // Modal
    newNotebookModal: document.querySelector('#newNotebookModal'),
    btnCloseModal: document.querySelector('#btnCloseModal'),
    btnCancelModal: document.querySelector('#btnCancelModal'),
    btnConfirmNewNotebook: document.querySelector('#btnConfirmNewNotebook'),
    newNotebookTitle: document.querySelector('#newNotebookTitle'),
    newNotebookCategory: document.querySelector('#newNotebookCategory'),
    newNotebookTemplate: document.querySelector('#newNotebookTemplate'),

    deleteNotebookModal: document.querySelector('#deleteNotebookModal'),
    deleteModalBookTitle: document.querySelector('#deleteModalBookTitle'),
    deleteModalPageCount: document.querySelector('#deleteModalPageCount'),
    btnCloseDeleteModal: document.querySelector('#btnCloseDeleteModal'),
    btnCancelDeleteModal: document.querySelector('#btnCancelDeleteModal'),
    btnConfirmDeleteModal: document.querySelector('#btnConfirmDeleteModal'),

    // Change Password Modal
    btnOpenChangePassword: document.querySelector('#btnOpenChangePassword'),
    changePasswordModal: document.querySelector('#changePasswordModal'),
    changePasswordForm: document.querySelector('#changePasswordForm'),
    oldPasswordInput: document.querySelector('#oldPasswordInput'),
    newPasswordInput: document.querySelector('#newPasswordInput'),
    confirmNewPasswordInput: document.querySelector('#confirmNewPasswordInput'),
    changePasswordError: document.querySelector('#changePasswordError'),
    btnCloseChangePasswordModal: document.querySelector('#btnCloseChangePasswordModal'),
    btnCancelChangePassword: document.querySelector('#btnCancelChangePassword'),
    btnSubmitChangePassword: document.querySelector('#btnSubmitChangePassword'),

    // Feedback
    appToast: document.querySelector('#appToast'),
    appToastText: document.querySelector('#appToastText'),
    appToastAction: document.querySelector('#appToastAction')
  };

  return cachedEls;
}
